ReferenceError: DOMMatrix is not defined     at [project]/node_modules/pdfjs-dist/build/pdf.mjs [app-ssr] (ecmascript) (file:///home/user/studio/.next/server/chunks/ssr/node_modules_pdfjs-dist_build_pdf_mjs_8b292815._.js:7741:22)     at instantiateModule (/home/user/studio/.next/server/chunks/ssr/[turbopack]_runtime.js:593:23)     at getOrInstantiateModuleFromParent (/home/user/studio/.next/server/chunks/ssr/[turbopack]_runtime.js:652:12)     at esmImport (/home/user/studio/.next/server/chunks/ssr/[turbopack]_runtime.js:132:20)     at [project]/src/app/page.tsx [app-ssr] (ecmascript) (file:///home/user/studio/.next/server/chunks/ssr/%5Broot%20of%20the%20server%5D__4cab385b._.js:414:172)     at instantiateModule (/home/user/studio/.next/server/chunks/ssr/[turbopack]_runtime.js:593:23)     at getOrInstantiateModuleFromParent (/home/user/studio/.next/server/chunks/ssr/[turbopack]_runtime.js:652:12)     at commonJsRequire (/home/user/studio/.next/server/chunks/ssr/[turbopack]_runtime.js:147:20)     at require (/home/user/studio/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:443:15880)     at requireModule (/home/user/studio/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:206:1036)     at initializeModuleChunk (/home/user/studio/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:206:25809)     at resolveModuleChunk (/home/user/studio/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:206:24944)     at /home/user/studio/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:206:54326     at AppDevOverlay (https://6000-idx-studio-1744438779694.cluster-a3grjzek65cxex762e4mwrzl46.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:14139:55)     at HotReload (https://6000-idx-studio-1744438779694.cluster-a3grjzek65cxex762e4mwrzl46.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:15058:50)     at Router (https://6000-idx-studio-1744438779694.cluster-a3grjzek65cxex762e4mwrzl46.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:15624:53)     at AppRouter (https://6000-idx-studio-1744438779694.cluster-a3grjzek65cxex762e4mwrzl46.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:15667:53)     at ServerRoot (https://6000-idx-studio-1744438779694.cluster-a3grjzek65cxex762e4mwrzl46.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:18361:54)